.TH "DNSGRAM" "1" "April 2015" "" ""
.SH NAME
.PP
\f[B]dnsgram\f[] \- A debugging tool for intermittent resolver failures
.SH SYNOPSIS
.PP
\f[B]dnsgram\f[] \f[I]INFILE\f[]...
.SH DESCRIPTION
.PP
\f[B]dnsgram\f[] takes one or more \f[I]INFILE\f[]s in PCAP format and
generates statistics on 5 second segments allowing the study of
intermittent resolver issues.
.SH OPTIONS
.PP
None
.SH SEE ALSO
.PP
pcap(3PCAP), tcpdump(8)
.SH AUTHORS
PowerDNS.com BV.
