.TH "DNSPCAP2PROTOBUF" "1" "June 2016" "" ""
.SH NAME
.PP
\f[B]dnspcap2protobuf\f[] \- A tool to convert PCAPs of DNS traffic to
PowerDNS Protobuf
.SH SYNOPSIS
.PP
\f[B]dnspcap2protobuf\f[] \f[I]PCAPFILE\f[] \f[I]OUTFILE\f[]
.SH DESCRIPTION
.PP
\f[B]dnspcap2protobuf\f[] reads the PCAP file \f[I]PCAPFILE\f[] for DNS
queries and responses and writes these in the PowerDNS protobuf format
to \f[I]OUTFILE\f[].
.SH OPTIONS
.TP
.B \-\-help
Show a summary of options.
.RS
.RE
.TP
.B \-\-version
Display the version of dnspcap2protobuf
.RS
.RE
.SH AUTHORS
PowerDNS.com BV.
