.TH "DNSSCAN" "1" "April 2015" "" ""
.SH NAME
.PP
\f[B]dnsscan\f[] \- List the amount of queries per qtype in a pcap
.SH SYNOPSIS
.PP
\f[B]dnsscan\f[] \f[I]INFILE\f[]...
.SH DESCRIPTION
.PP
\f[B]dnsscan\f[] takes one or more \f[I]INFILE\f[]s in PCAP format and
generates a list of the number of queries per qtype.
.SH OPTIONS
.PP
None
.SH SEE ALSO
.PP
pcap(3PCAP), tcpdump(8)
.SH AUTHORS
PowerDNS.com BV.
