.TH "DNSWASHER" "1" "September 2012" "" ""
.SH NAME
.PP
\f[B]dnswasher\f[] \- A PowerDNS nameserver debugging tool
.SH SYNOPSIS
.PP
\f[B]dnswasher\f[] \f[I]INFILE\f[] [\f[I]INFILE\f[]] \f[I]OUTFILE\f[]
.SH DESCRIPTION
.PP
dnswasher takes one or more \f[I]INFILE\f[]s in PCAP format and writes
out \f[I]OUTFILE\f[] also in PCAP format, while obfuscating end\-user IP
addresses.
.PP
This is useful to share data with third parties while attempting to
protect the privacy of your users.
.PP
The INFILEs must be of identical PCAP type.
.PP
Please check the output of \f[B]dnswasher\f[] to make sure no customer
IP addresses remain.
Also realize that sufficient data could allow individuals to be
re\-identified based on the domain names they care about.
.SH OPTIONS
.PP
None
.SH SEE ALSO
.PP
pcap(3PCAP), tcpdump(8)
.SH AUTHORS
Joerg Jungermann (jj+debian At borkum.net).
