.TH "PDNS_NOTIFY" "1" "April 2016" "" ""
.SH NAME
.PP
\f[B]pdns_notify\f[] \- A simple DNS NOTIFY sender
.SH SYNOPSIS
.PP
\f[B]pdns_notify\f[] \f[I]IP_ADDRESS\f[][:\f[I]PORT\f[]] \f[I]DOMAIN\f[]
.SH DESCRIPTION
.PP
\f[B]pdns_notify\f[] sends a DNS NOTIFY message to \f[I]IP_ADDRESS\f[],
by default on port 53, for \f[I]DOMAIN\f[] and prints the remote
nameserver\[aq]s response.
.SH OPTIONS
.PP
None
.SH AUTHORS
PowerDNS.com BV.
